//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClarityData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClarityData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is freeware.
        /// </summary>
        internal static string ClarityDataParser_aboutToolStripMenuItem_Click_Product_is_freeware {
            get {
                return ResourceManager.GetString("ClarityDataParser_aboutToolStripMenuItem_Click_Product_is_freeware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        internal static string ClarityDataParser_ParseReportClick__csv {
            get {
                return ResourceManager.GetString("ClarityDataParser_ParseReportClick__csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file ready.
        /// </summary>
        internal static string ClarityDataParser_ParseReportClick_Output_file_ready {
            get {
                return ResourceManager.GetString("ClarityDataParser_ParseReportClick_Output_file_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing File:.
        /// </summary>
        internal static string ClarityDataParser_ParseReportClick_Processing_File_ {
            get {
                return ResourceManager.GetString("ClarityDataParser_ParseReportClick_Processing_File_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . 
        /// Remaining mails to be processed: .
        /// </summary>
        internal static string ClarityFunctions_GetAttachments_ {
            get {
                return ResourceManager.GetString("ClarityFunctions_GetAttachments_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ready to process the file. .
        /// </summary>
        internal static string ClarityFunctions_GetAttachments__Ready_to_process_the_file__ {
            get {
                return ResourceManager.GetString("ClarityFunctions_GetAttachments__Ready_to_process_the_file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Attachment: .
        /// </summary>
        internal static string ClarityFunctions_GetAttachments_Getting_Attachment__ {
            get {
                return ResourceManager.GetString("ClarityFunctions_GetAttachments_Getting_Attachment__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail attachments downloaded.
        /// </summary>
        internal static string ClarityFunctions_GetAttachments_Mail_attachments_downloaded {
            get {
                return ResourceManager.GetString("ClarityFunctions_GetAttachments_Mail_attachments_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No New mails.
        /// </summary>
        internal static string ClarityFunctions_GetAttachments_No_New_mails {
            get {
                return ResourceManager.GetString("ClarityFunctions_GetAttachments_No_New_mails", resourceCulture);
            }
        }
    }
}
